site_name: xDrip4iOS
theme: readthedocs
extra_css:
    - css/admonitions.css
markdown_extensions:
    - admonition
    - toc:
        permalink: ⌁

pages:
- 'Introduction': 'index.md'
- Install: 
    - 'Install from Testflight': 'install/testflight.md'
    - 'Build from Source': 'install/build.md'
- Connect:
    - 'Introduction': 'connect/index.md'
    - 'Connect to CGM as a Master': 'connect/cgm.md'
    - 'Connect to Nightscout as a Follower': 'connect/follower.md'
    - 'Connect to M5Stack': 'connect/m5stack.md'
- Configure/Use:
    - 'General': 'configure/index.md'
    - 'Alarms': 'configure/alarms.md'
    - 'Data Sharing': 'configure/share.md'
    - 'Calibration': 'configure/calibrate.md'
    - 'Apple Watch': 'configure/applewatch.md'
    - 'Other Smartwatches': 'configure/smartwatches.md'
    - 'FreeAPS Integration': 'configure/freeaps.md'
- Use and Troubleshoot:
    - 'Troubleshooting': 'troubleshooting/index.md'
    - 'Cannot Connect?': 'troubleshooting/connection_troubles.md'
    - 'Disconnections?': 'troubleshooting/disconnections.md'
    - 'How to send an Issue Report': 'troubleshooting/issue_report.md'
